from typing import Protocol, Any
from datetime import datetime


class WbReturnsPort(Protocol):
    async def get_open_claims(self) -> list[dict[str, Any]]: ...
    async def answer_claim(self, claim_id: str, action: str, comment: str | None) -> dict[str, Any]: ...

class ClaimsRepoPort(Protocol):
    async def was_processed(self, claim_id: str) -> bool: ...
    async def mark_done(self, claim_id: str, action: str, processed_at: datetime) -> None: ...
    async def mark_failed(self, claim_id: str, error: str, processed_at: datetime) -> None: ...

class NotifierPort(Protocol):
    async def notify_admins(self, text: str) -> None: ...